services:
  app:
    build: .
# Assigning the name to the container:
    container_name: netflix_analytics   

# Mapping ports on your cpu to port 8501 inside the container
    ports:
      - "8501:8501"

# Syncs the cpu/local project folder with the container
    volumes:
      - .:/app
      - /app/.venv    # this was inside the container at first and localhost could not work
